### ISSUE TITLE
secrets.h missing

### ISSUE THREAD

**Issue by mozexty** [Aces-Electronics/AE-ESP32-S3-SIM7670G-4G#1]
I'm trying to build this code using plaformio, and I have an error :
**src/main.cpp:20:10: fatal error: secrets.h: No such file or directory**

How to deal with that ?

**Comment by 84ace** [comment]
Sorry for the slow reply. I didn't get a notification.

You'll just need to create the file and put the following in it:
```
#include <Arduino.h>
String secretServerURL = "http://a.b.c.d";
```

Where A.B.C.D is the IP of the server that you are sending the data to.

**Comment by mozexty** [comment]
Thank you
